#!/bin/sh
# Copyright (c) 2012 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Generates font source images.

SCRIPT="$(readlink -f "$0")"
SCRIPT_DIR="$(dirname "$SCRIPT")"
FIRST_ASCII_GLYPH="32" # space
LAST_ASCII_GLYPH="127" # delete
if [ -z "${MENU_UI}" ]; then
  FGCOLOR="#505050"
  BGCOLOR="#ffffff"
  FONT="Noto Sans"
  MARGIN="3 0"
else
  # The colors will be adjusted at runtime.
  FGCOLOR="#ffffff"
  BGCOLOR="#000000"
  FONT="Noto Sans Mono"
  MARGIN="-3 0 -1 0"
fi

die() {
  echo "ERROR: $*" >&2
  exit 1
}

main() {
  [ "$#" = "1" ] || die "Usage: $0 output_dir"
  local output="$1"
  mkdir -p "$output"

  local glyph="$FIRST_ASCII_GLYPH"
  local c=''
  local name=''
  local fontsize=""
  echo "Generating glyph text source..."
  while [[ "$glyph"  != "$LAST_ASCII_GLYPH" ]]; do
    c=$(printf "\x$(printf %x $glyph)")
    name="idx$(printf "%03d" $glyph)_$(printf "%x" $glyph)"
    echo "$c" >"$output/$name.txt"
    glyph=$((glyph + 1))
  done

  [ -n "$FONTSIZE" ] && fontsize="--point=$FONTSIZE"

  echo "Converting glyph images..."

  "$SCRIPT_DIR/text_to_png_svg" --font="$FONT" --color="$FGCOLOR" \
    --bgcolor="$BGCOLOR" --margin="$MARGIN" --outdir="$output" \
    $fontsize "$output/*.txt"
}

set -e
main "$@"
